default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: bookshelf_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: bookshelf_test
  pool: 5
  username: postgres
  password: password

production:
  <<: *default
  database: bookshelf
  encoding: unicode
  username: postgres
  password: password
